### ISSUE TITLE
`update!(::StepTaker,...)` is not actually called

### ISSUE THREAD

**Issue by lukas-weber** [gamatos/Basinhopping.jl#1]
I noticed that the call to `update!` is commented out in
https://github.com/gamatos/Basinhopping.jl/blob/8c8028271f6dc02d22f612c080dc7856d9be31b8/src/Basinhopping.jl#L314

So the feature is never actually active, which is at odds with the documentation.

**Comment by gamatos** [comment]
Hi @lukas-weber, thank you for pointing this out. That line should indeed not have been commented out. Apologies for any inconvenience this might have caused, I will shortly push a fix and update the package.

**Comment by gamatos** [comment]
Fixed in [v0.1.1](https://github.com/gamatos/Basinhopping.jl/releases/tag/v0.1.1).

**Comment by lukas-weber** [comment]
Thanks so much for the quick fix! :smile:
